services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    Helis\SettingsManagerBundle\Controller\DomainController:
        arguments:
            $twig: '@twig'
            $formFactory: '@form.factory'
            $urlGenerator: '@router'
            $settingsManager: '@Helis\SettingsManagerBundle\Settings\SettingsManager'
        public: true

    Helis\SettingsManagerBundle\Controller\SettingsController:
        arguments:
            $twig: '@twig'
            $formFactory: '@form.factory'
            $urlGenerator: '@router'
            $settingsManager: '@Helis\SettingsManagerBundle\Settings\SettingsManager'
            $eventManager: '@Helis\SettingsManagerBundle\Settings\EventManagerInterface'
            $validator: '@validator'
        public: true
