services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    Helis\SettingsManagerBundle\Controller\DomainController:
        public: true
        arguments:
            $settingsManager: '@Helis\SettingsManagerBundle\Settings\SettingsManager'
        tags:
            - { name: controller.service_arguments }

    Helis\SettingsManagerBundle\Controller\SettingsController:
        public: true
        arguments:
            $settingsManager: '@Helis\SettingsManagerBundle\Settings\SettingsManager'
            $eventDispatcher: '@event_dispatcher'
            $validator: '@validator'
        tags:
            - { name: controller.service_arguments }

    Helis\SettingsManagerBundle\Settings\SettingsAwareServiceFactory:
        arguments:
            $settingsRouter: '@Helis\SettingsManagerBundle\Settings\SettingsRouter'
        calls:
            - [setLogger, ['@?settings_manager.logger']]

    Helis\SettingsManagerBundle\Settings\SettingsStore: ~

    Helis\SettingsManagerBundle\Settings\ProvidersManager:
        arguments:
            $settingsManager: '@Helis\SettingsManagerBundle\Settings\SettingsManager'
